spring:
    jpa:
        show_sql: true

    h2:
        console:
            enabled: true

    profiles:
        include: oauth

server:
    servlet:
        encoding:
            force-response: true

    use-forward-headers: true