spring:
    jpa:
        show_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    h2:
        console:
            enabled: true

    profiles:
        include: 
            - oauth
    session:
        store-type: jdbc

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: test
                        client-secret: test
                        scope:
                            - profile
                            - email

server:
    servlet:
        encoding:
            force-response: true

    use-forward-headers: true